# Generated by Django 2.2.6 on 2019-10-16 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalURL',
            fields=[
                ('original_url', models.CharField(max_length=500, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Original URLS',
            },
        ),
        migrations.CreateModel(
            name='URLid',
            fields=[
                ('original_url', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='URLShortner.OriginalURL')),
                ('url_id', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'URLid',
            },
        ),
    ]
